name: e_comerce_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  firebase_auth: ^3.3.20
  firebase_core:
  get: ^4.6.1
  salomon_bottom_bar: ^3.3.0
  cloud_firestore: ^3.1.17
  sqflite: ^2.0.0+4
  share: ^2.0.4
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/nav_bar/
      - assets/images/
      - assets/images/categories_images/
      - assets/images/grocery_images/
      - assets/images/beverages_images/
      - assets/icons/
      - assets/icons/account_icons/
      - assets/fonts/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/gilroy/Pacifico-Regular.ttf